// 라파엘박물관 소장품 목록
const ARTWORK_SECTIONS = [
  {
    id: "school-days",
    theme: "학창시절 테마",
    title: "청춘의 성물",
    titleEn: "Relics of Youth",
    description:
      "교실, 운동장, 식탁, 캠퍼스의 시간이 하나의 사적인 신화로 변하는 첫 번째 전시관.",
    artworks: [
      {
        id: "primordial-yuchan",
        file: "assets/유찬원본 (1).jpg",
        title: "원형의 초상",
        titleEn: "The Primordial Portrait",
        era: "제1관 · 기원의 방",
        description: "모든 변주가 태어나기 전의 얼굴. 라파엘박물관 전체 세계관의 출발점이 되는 원본 초상.",
        featured: true,
      },
      {
        id: "kyungpook-scholar",
        file: "assets/경북대 유찬 (1).png",
        title: "캠퍼스의 현자",
        titleEn: "Sage of the Campus",
        era: "제1관 · 학문의 뜰",
        description: "경북대의 공기 속에서 지성과 야망이 조용히 빛나는 청춘기의 학문적 초상.",
      },
      {
        id: "midnight-study",
        file: "assets/열공 유찬 (1).png",
        title: "심야의 필사본",
        titleEn: "Manuscript at Midnight",
        era: "제1관 · 시험의 밤",
        description: "책상 위의 불빛 아래 집중이 의식처럼 이어지는 장면. 노력 그 자체를 성물로 만든 작품.",
      },
      {
        id: "construction-youth",
        file: "assets/공사 유찬 (1).png",
        title: "미완의 공사장",
        titleEn: "The Unfinished Site",
        era: "제1관 · 성장의 구조물",
        description: "아직 완성되지 않은 청춘의 골조. 먼지와 철골 사이에서 미래가 천천히 세워진다.",
      },
      {
        id: "baseball-prospect",
        file: "assets/야구선수 유찬 (1).png",
        title: "다이아몬드의 신동",
        titleEn: "Prodigy of the Diamond",
        era: "제1관 · 운동장의 전설",
        description: "승부의 긴장과 소년의 자신감이 포개진 스포츠 성화. 한 번의 스윙이 신화가 된다.",
      },
      {
        id: "billiard-tournament",
        file: "assets/당구대회 유찬 (1).png",
        title: "녹색 당구대의 결승",
        titleEn: "Final on the Green Table",
        era: "제1관 · 승부의 홀",
        description: "큐 끝에 집중된 침묵과 계산. 친구들의 박수보다 더 큰 운명이 테이블 위를 돈다.",
      },
      {
        id: "billiard-study",
        file: "assets/당구 유찬 (1).png",
        title: "세 각도의 철학",
        titleEn: "Philosophy in Three Cushions",
        era: "제1관 · 놀이의 기하학",
        description: "가벼운 놀이가 정교한 사유로 바뀌는 순간. 공의 궤적은 작은 우주가 된다.",
      },
      {
        id: "podcast-youth",
        file: "assets/유찬 팟캐스트 (1).png",
        title: "방송실의 계시",
        titleEn: "Revelation in the Studio",
        era: "제1관 · 목소리의 기록",
        description: "마이크 앞에 놓인 청춘의 언어. 농담과 확신이 전파처럼 퍼져 나간다.",
      },
      {
        id: "pilot-yuchan",
        file: "assets/조종사 유찬 (1).png",
        title: "구름 위의 조종석",
        titleEn: "Cockpit Above the Clouds",
        era: "제1관 · 비상의 꿈",
        description: "평범한 하루를 벗어나 하늘을 향해 몸을 기울이는 장면. 꿈은 이미 이륙 중이다.",
      },
      {
        id: "sink-ritual",
        file: "assets/유찬설거지 (1).png",
        title: "설거지의 정결례",
        titleEn: "The Rite of Washing",
        era: "제1관 · 일상의 제단",
        description: "가장 생활적인 노동이 의식처럼 빛나는 작품. 물소리 속에서 하루가 정리된다.",
      },
      {
        id: "birthday-litany",
        file: "assets/생일축하유찬 (1).png",
        title: "생일의 작은 대관식",
        titleEn: "A Small Coronation",
        era: "제1관 · 축하의 방",
        description: "촛불과 축하 속에서 한 시절이 왕관처럼 얹힌다. 사소하지만 또렷한 기념비.",
      },
      {
        id: "first-romance",
        file: "assets/여자친구생긴유찬 (1).png",
        title: "첫 로맨스의 증언",
        titleEn: "Testimony of First Romance",
        era: "제1관 · 마음의 회랑",
        description: "사적인 설렘이 전시 가능한 사건이 되는 순간. 표정 하나가 계절을 바꾼다.",
      },
      {
        id: "anchovy-icon",
        file: "assets/유찬멸치 (1).jpg",
        title: "마른 빛의 성자",
        titleEn: "Saint of Lean Light",
        era: "제1관 · 유머의 성물",
        description: "가볍고 날렵한 이미지가 아이콘으로 승격된다. 웃음과 애정이 함께 보존된 소품.",
      },
      {
        id: "giant-yuchan",
        file: "assets/거인 유찬 (1).png",
        title: "운동장 위의 거인",
        titleEn: "Giant Over the Yard",
        era: "제1관 · 확대된 전설",
        description: "청춘의 존재감이 실제보다 커지는 장면. 친구들의 기억 속 크기가 화면을 압도한다.",
      },
      {
        id: "molten-yuchan",
        file: "assets/녹은 유찬 (1).png",
        title: "녹아내린 오후",
        titleEn: "The Melted Afternoon",
        era: "제1관 · 피로와 해학",
        description: "시험, 더위, 장난이 뒤섞인 표정. 무너지는 순간마저 하나의 초상으로 남는다.",
      },
    ],
  },
  {
    id: "raphael-order",
    theme: "라파엘 종교 테마",
    title: "라파엘 교단 연대기",
    titleEn: "Chronicles of the Raphael Order",
    description:
      "한 인물이 교주, 순례자, 설계자, 논쟁가가 되어가는 장면들을 모은 두 번째 전시관.",
    artworks: [
      {
        id: "baptism-raphael",
        file: "assets/세례 유찬 (2).png",
        title: "라파엘의 세례",
        titleEn: "Baptism of Raphael",
        era: "제2관 · 입문의 물",
        description: "새로운 이름을 받는 의식. 물결과 후광 사이에서 교단의 첫 숨이 열린다.",
        featured: true,
      },
      {
        id: "founding-order",
        file: "assets/종교 창설 유찬 (2).png",
        title: "새 교단의 서막",
        titleEn: "Founding of the Order",
        era: "제2관 · 창설의 홀",
        description: "믿음이 조직이 되고 농담이 제도가 되는 순간. 라파엘 서사의 본격적인 출발점.",
      },
      {
        id: "supreme-guru",
        file: "assets/한국 1위 종교 교주 유찬 (2).png",
        title: "제1교주의 즉위",
        titleEn: "Enthronement of the First Guru",
        era: "제2관 · 권위의 단상",
        description: "과장된 위엄과 진지한 장난이 맞물린 초상. 교주의 자리가 하나의 무대가 된다.",
      },
      {
        id: "guru-room",
        file: "assets/라파엘 교주 방 (2).png",
        title: "성좌의 밀실",
        titleEn: "The Guru's Chamber",
        era: "제2관 · 내실의 기록",
        description: "교단의 중심부를 상상하게 하는 방. 조용한 사물들이 권위의 배경으로 배치된다.",
      },
      {
        id: "scripture-study",
        file: "assets/성경 공부 유찬 (2).png",
        title: "경전 연구",
        titleEn: "Study of the Scripture",
        era: "제2관 · 해석의 책상",
        description: "읽고 밑줄 긋고 다시 묻는 시간. 신앙보다 먼저 텍스트와 집중이 놓인다.",
      },
      {
        id: "praise-hymn",
        file: "assets/찬양유찬 (2).png",
        title: "밤의 찬가",
        titleEn: "Nocturne of Praise",
        era: "제2관 · 노래의 예배당",
        description: "목소리가 공간을 채우며 의식이 된다. 찬양은 장난스럽지만 화면은 진심에 가깝다.",
      },
      {
        id: "golden-blessing",
        file: "assets/축복 유찬 (2).png",
        title: "금빛 축도",
        titleEn: "Golden Benediction",
        era: "제2관 · 축복의 제단",
        description: "손짓 하나가 선언으로 변하는 순간. 관람자를 향한 축복이 금빛으로 내려앉는다.",
      },
      {
        id: "fallen-aura",
        file: "assets/타락 유찬 (2).png",
        title: "추락한 후광",
        titleEn: "The Fallen Halo",
        era: "제2관 · 의심의 계단",
        description: "성스러움이 흔들릴 때 생기는 드라마. 빛은 사라지지 않고 더 어둡게 빛난다.",
      },
      {
        id: "argument-with-priest",
        file: "assets/신부랑 싸우는 유찬 (2).png",
        title: "논쟁의 성찬",
        titleEn: "The Disputed Communion",
        era: "제2관 · 교리의 충돌",
        description: "믿음과 고집, 농담과 권위가 마주 선 장면. 교단의 서사는 여기서 인간적인 열을 얻는다.",
      },
      {
        id: "meeting-the-lord",
        file: "assets/주님과의 만남 유찬 (2).png",
        title: "응답의 문턱",
        titleEn: "Threshold of the Answer",
        era: "제2관 · 계시의 문",
        description: "누군가를 마주한 듯한 순간. 화면 바깥의 존재가 작품 전체를 조용히 당긴다.",
      },
      {
        id: "designer-of-vestments",
        file: "assets/디자이너 유찬 (2).png",
        title: "성의의 설계자",
        titleEn: "Designer of Vestments",
        era: "제2관 · 형식의 공방",
        description: "의복과 상징을 설계하는 또 다른 교주상. 믿음은 때로 스타일로 먼저 도착한다.",
      },
      {
        id: "bicycle-pilgrim",
        file: "assets/자전거 유찬 (2).png",
        title: "순례자의 바퀴",
        titleEn: "Wheels of the Pilgrim",
        era: "제2관 · 이동의 순례",
        description: "거창한 성지가 아니라 길 위에서 시작되는 순례. 자전거는 가장 경쾌한 성물이다.",
      },
    ],
  },
  {
    id: "sacred-icons",
    theme: "성스러운 종교 작품 테마",
    title: "성화와 묵시록",
    titleEn: "Sacred Icons and Apocalypse",
    description:
      "창조, 기적, 심판, 부활, 승천으로 이어지는 거대한 성화풍 서사의 마지막 전시관.",
    artworks: [
      {
        id: "raphael-avatar",
        file: "assets/라파엘유찬 (3).png",
        title: "라파엘의 현현",
        titleEn: "The Manifest Raphael",
        era: "제3관 · 대천사의 벽",
        description: "라파엘이라는 이름이 가장 직접적으로 드러나는 상징적 초상. 박물관의 이름을 떠받치는 성화.",
        featured: true,
      },
      {
        id: "creation-god",
        file: "assets/창조의 신 유찬 (3).png",
        title: "창조주의 손",
        titleEn: "Hand of the Creator",
        era: "제3관 · 창세의 천장",
        description: "무에서 세계가 열리는 장면을 유찬의 신화로 다시 쓴 작품. 빛의 시작을 다룬다.",
      },
      {
        id: "holy-yuchan",
        file: "assets/성스러운 유찬이 (3).png",
        title: "성스러운 유찬",
        titleEn: "The Sacred Yuchan",
        era: "제3관 · 성자의 초상",
        description: "정면성, 후광, 고요한 표정이 성상처럼 배치된다. 장난스러움보다 경건함이 먼저 다가온다.",
      },
      {
        id: "angel-yuchan",
        file: "assets/천사유찬 (3).png",
        title: "날개 달린 사자",
        titleEn: "The Winged Messenger",
        era: "제3관 · 천사의 회랑",
        description: "천사의 이미지와 인간적 표정이 겹친 초상. 하늘의 전령이 잠시 친구의 얼굴을 빌린다.",
      },
      {
        id: "angelic-guard",
        file: "assets/천사의 가호 유찬 (3).png",
        title: "천사의 가호",
        titleEn: "Angelic Protection",
        era: "제3관 · 보호의 장막",
        description: "위험보다 보호가 먼저 느껴지는 장면. 빛은 방패처럼 인물을 둘러싼다.",
      },
      {
        id: "hanjunhee-blessing",
        file: "assets/한준희의 가호 유찬 (3).png",
        title: "한준희의 가호",
        titleEn: "Blessing of Han Junhee",
        era: "제3관 · 수호자의 이름",
        description: "개인적 기억이 성스러운 보호의 언어로 바뀐 작품. 이름 하나가 부적처럼 작동한다.",
      },
      {
        id: "moses-miracle",
        file: "assets/모세의 기적 유찬 (3).png",
        title: "갈라진 바다의 예언자",
        titleEn: "Prophet of the Divided Sea",
        era: "제3관 · 기적의 물길",
        description: "모세의 서사를 유찬의 얼굴로 옮긴 대형 성화. 길이 없던 곳에 길이 열린다.",
      },
      {
        id: "five-loaves",
        file: "assets/오병이어 유찬 (3).png",
        title: "오병이어의 식탁",
        titleEn: "Table of Five Loaves",
        era: "제3관 · 풍요의 기적",
        description: "부족한 것이 넘치는 것으로 바뀌는 순간. 식탁은 기적이 발생하는 가장 현실적인 장소다.",
      },
      {
        id: "last-supper",
        file: "assets/최후의만찬 유찬 (3).png",
        title: "최후의 만찬",
        titleEn: "The Last Supper of Yuchan",
        era: "제3관 · 마지막 식탁",
        description: "고전 성화의 구도를 유찬 신화로 다시 배열한 작품. 엄숙함과 패러디가 정면으로 만난다.",
      },
      {
        id: "wilderness",
        file: "assets/광야 유찬 (3).png",
        title: "광야의 시험",
        titleEn: "Trial in the Wilderness",
        era: "제3관 · 침묵의 사막",
        description: "비어 있는 공간에서 내면의 소리가 커지는 장면. 광야는 고립이 아니라 통과의례다.",
      },
      {
        id: "prayer",
        file: "assets/기도 유찬 (3).png",
        title: "침묵의 기도",
        titleEn: "Prayer in Silence",
        era: "제3관 · 내면의 제단",
        description: "말보다 자세가 먼저 전해지는 작품. 고요함이 화면의 중심을 붙잡는다.",
      },
      {
        id: "sacrificial-rite",
        file: "assets/제사 유찬 (3).png",
        title: "제사의 불빛",
        titleEn: "Light of the Offering",
        era: "제3관 · 봉헌의 밤",
        description: "무언가를 바치는 행위가 어둠 속에서 빛난다. 의식의 열기가 화면에 남는다.",
      },
      {
        id: "ark-builder",
        file: "assets/방주 건축 유찬 (3).png",
        title: "방주의 건축가",
        titleEn: "Architect of the Ark",
        era: "제3관 · 대홍수 이전",
        description: "다가올 재난을 알고 준비하는 인물. 나무와 설계도 사이에서 구원의 형태가 만들어진다.",
      },
      {
        id: "afterglow",
        file: "assets/후광 유찬 (3).png",
        title: "황금 후광",
        titleEn: "The Golden Halo",
        era: "제3관 · 빛의 원환",
        description: "인물 뒤편의 빛이 왕관처럼 번진다. 성스러움이 가장 간결한 형태로 응축된 작품.",
      },
      {
        id: "end-of-world",
        file: "assets/세상멸망 유찬 (3).png",
        title: "세계의 종말",
        titleEn: "End of the World",
        era: "제3관 · 묵시록",
        description: "모든 질서가 무너지는 장면. 파국은 끝이 아니라 다음 신화를 위한 어두운 배경이 된다.",
      },
      {
        id: "resurrection",
        file: "assets/부활 유찬 (3).png",
        title: "부활의 새벽",
        titleEn: "Dawn of Resurrection",
        era: "제3관 · 다시 열린 빛",
        description: "무너진 뒤 다시 떠오르는 장면. 어둠의 무게 때문에 빛은 더 분명해진다.",
      },
      {
        id: "ascension",
        file: "assets/승천 유찬 (3).png",
        title: "승천",
        titleEn: "The Ascension",
        era: "제3관 · 하늘의 문",
        description: "지상의 서사가 하늘로 옮겨지는 순간. 전시의 종착점이자 가장 높은 장면.",
      },
      {
        id: "jeezus-yuchan",
        file: "assets/지저스유찬 (3).png",
        title: "지저스 유찬",
        titleEn: "Jeezus Yuchan",
        era: "제3관 · 구원의 초상",
        description: "익숙한 구원자의 이미지가 유찬의 얼굴과 겹친다. 패러디와 경건함이 가장 대담하게 공존한다.",
      },
    ],
  },
];
